/* eslint-disable */
// Generated by @convex-dev/cli@0.0.51
// based on the contents of this directory
import type getCounter from "./getCounter";
import type incrementCounter from "./incrementCounter";

type ConvexAPI = {
  queries: {
    getCounter: typeof getCounter;
  };
  mutations: {
    incrementCounter: typeof incrementCounter;
  };
};

import {
  makeUseQuery,
  makeUseMutation,
  makeUseConvex,
} from "@convex-dev/react";

export const useQuery = makeUseQuery<ConvexAPI>();
export const useMutation = makeUseMutation<ConvexAPI>();
export const useConvex = makeUseConvex<ConvexAPI>();
