/* eslint-disable */
// Generated by @convex-dev/cli@0.0.62
// based on the contents of this directory.
// To regenerate, run `convex codegen`.
import type getCounter from "./getCounter";
import type incrementCounter from "./incrementCounter";

import type { MutationCtx, QueryCtx } from "@convex-dev/server";
type DropFirst<T extends unknown[]> = T extends [any, ...infer U] ? U : never;
type ClientMutation<F extends (first: MutationCtx, ...args: any) => any> = (
  ...args: DropFirst<Parameters<F>>
) => ReturnType<F>;
type ClientQuery<F extends (first: QueryCtx, ...args: any) => any> = (
  ...args: DropFirst<Parameters<F>>
) => ReturnType<F>;

type ConvexAPI = {
  queries: {
    getCounter: ClientQuery<typeof getCounter>;
  };
  mutations: {
    incrementCounter: ClientMutation<typeof incrementCounter>;
  };
};

import {
  makeUseQuery,
  makeUseMutation,
  makeUseConvex,
} from "@convex-dev/react";

export const useQuery = makeUseQuery<ConvexAPI>();
export const useMutation = makeUseMutation<ConvexAPI>();
export const useConvex = makeUseConvex<ConvexAPI>();
