/* eslint-disable */
/**
 * Generated development client configuration.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@0.1.10.
 * To regenerate, run `npx convex codegen`.
 * @module
 */

import type { ClientConfiguration } from "convex/browser";

/**
 * The DEVELOPMENT Convex client configuration.
 *
 * This configuration connects your client to your development Convex deployment
 * when `npx convex dev` is running.
 *
 * To generate the production version, run `npx convex deploy`.
 *
 * Usage:
 *
 * ```ts
 * import clientConfig from "../convex/_generated/clientConfig";
 *
 * const convex = new ConvexReactClient(clientConfig);
 * ```
 */
const clientConfig: ClientConfiguration = {
  address: "http://localhost:8187",
};
export default clientConfig;
