/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.3.1.
 * To regenerate, run `npx convex dev`.
 * @module
 */

const { anyApi } = require("convex/server");
module.exports = {
  api: anyApi,
  internal: anyApi,
};
