/* eslint-disable */
// Generated by @convex-dev/cli@0.0.56
// based on the contents of this directory.
// To regenerate, run `convex codegen`.
import type addChannel from "./addChannel";
import type listChannels from "./listChannels";
import type listMessages from "./listMessages";
import type sendMessage from "./sendMessage";
import type storeUser from "./storeUser";

type ConvexAPI = {
  queries: {
    listChannels: typeof listChannels;
    listMessages: typeof listMessages;
  };
  mutations: {
    addChannel: typeof addChannel;
    sendMessage: typeof sendMessage;
    storeUser: typeof storeUser;
  };
};

import {
  makeUseQuery,
  makeUseMutation,
  makeUseConvex,
} from "@convex-dev/react";

export const useQuery = makeUseQuery<ConvexAPI>();
export const useMutation = makeUseMutation<ConvexAPI>();
export const useConvex = makeUseConvex<ConvexAPI>();
